version: "3"
networks:
  api_server_default:
    external: true
services:
  fandom:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV_NAME: dev
    ports:
      - 4001:4001
